/* Generated by Yosys 0.25+99 (git sha1 54bf15a5b, x86_64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "adder_8bit.v:1.1-24.10" *)
module adder8(A, B, SUM);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "adder_8bit.v:2.17-2.18" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "adder_8bit.v:3.17-3.18" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "adder_8bit.v:4.18-4.21" *)
  output [7:0] SUM;
  wire [7:0] SUM;
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _082_ (
    .A(A[7]),
    .B(A[7]),
    .Y(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _083_ (
    .A(B[7]),
    .B(B[7]),
    .Y(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _084_ (
    .A(B[0]),
    .B(B[0]),
    .Y(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _085_ (
    .A(B[1]),
    .B(B[1]),
    .Y(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _086_ (
    .A(B[2]),
    .B(B[2]),
    .Y(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _087_ (
    .A(B[3]),
    .B(B[3]),
    .Y(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _088_ (
    .A(A[1]),
    .B(A[1]),
    .Y(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _089_ (
    .A(A[0]),
    .B(A[0]),
    .Y(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _090_ (
    .A(A[3]),
    .B(A[3]),
    .Y(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _091_ (
    .A(A[2]),
    .B(A[2]),
    .Y(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _092_ (
    .A(A[5]),
    .B(A[5]),
    .Y(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _093_ (
    .A(A[4]),
    .B(A[4]),
    .Y(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _094_ (
    .A(A[6]),
    .B(A[6]),
    .Y(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _095_ (
    .A(B[5]),
    .B(B[5]),
    .Y(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _096_ (
    .A(B[4]),
    .B(B[4]),
    .Y(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _097_ (
    .A(B[6]),
    .B(B[6]),
    .Y(_026_)
  );
  NAND _098_ (
    .A(A[7]),
    .B(B[7]),
    .Y(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _099_ (
    .A(_027_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _100_ (
    .A(A[6]),
    .B(B[6]),
    .Y(_029_)
  );
  NAND _101_ (
    .A(A[5]),
    .B(B[5]),
    .Y(_030_)
  );
  NAND _102_ (
    .A(A[4]),
    .B(B[4]),
    .Y(_031_)
  );
  NAND _103_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_032_)
  );
  NAND _104_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_033_)
  );
  NAND _105_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_034_)
  );
  NAND _106_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _107_ (
    .A(_035_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _108_ (
    .A(_014_),
    .B(_017_),
    .Y(_037_)
  );
  NAND _109_ (
    .A(_034_),
    .B(_037_),
    .Y(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _110_ (
    .A(_038_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _111_ (
    .A(_036_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _112_ (
    .A(_034_),
    .B(_040_),
    .Y(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _113_ (
    .A(_041_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _114_ (
    .A(_015_),
    .B(_020_),
    .Y(_043_)
  );
  NAND _115_ (
    .A(_033_),
    .B(_043_),
    .Y(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _116_ (
    .A(_044_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _117_ (
    .A(_041_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _118_ (
    .A(_033_),
    .B(_046_),
    .Y(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _119_ (
    .A(_047_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _120_ (
    .A(_016_),
    .B(_019_),
    .Y(_049_)
  );
  NAND _121_ (
    .A(_032_),
    .B(_049_),
    .Y(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _122_ (
    .A(_050_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _123_ (
    .A(_047_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _124_ (
    .A(_032_),
    .B(_052_),
    .Y(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _125_ (
    .A(_053_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _126_ (
    .A(_022_),
    .B(_025_),
    .Y(_055_)
  );
  NAND _127_ (
    .A(_031_),
    .B(_055_),
    .Y(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _128_ (
    .A(_056_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _129_ (
    .A(_053_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _130_ (
    .A(_031_),
    .B(_058_),
    .Y(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _131_ (
    .A(_059_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _132_ (
    .A(_021_),
    .B(_024_),
    .Y(_061_)
  );
  NAND _133_ (
    .A(_030_),
    .B(_061_),
    .Y(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _134_ (
    .A(_062_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _135_ (
    .A(_059_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _136_ (
    .A(_030_),
    .B(_064_),
    .Y(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _137_ (
    .A(_065_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _138_ (
    .A(_023_),
    .B(_026_),
    .Y(_067_)
  );
  NAND _139_ (
    .A(_029_),
    .B(_067_),
    .Y(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _140_ (
    .A(_068_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _141_ (
    .A(_065_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _142_ (
    .A(_029_),
    .B(_070_),
    .Y(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _143_ (
    .A(_071_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _144_ (
    .A(_028_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _145_ (
    .A(_013_),
    .B(_018_),
    .Y(_074_)
  );
  NAND _146_ (
    .A(_035_),
    .B(_074_),
    .Y(_075_)
  );
  NAND _147_ (
    .A(_073_),
    .B(_075_),
    .Y(SUM[0])
  );
  NAND _148_ (
    .A(_035_),
    .B(_038_),
    .Y(_076_)
  );
  NAND _149_ (
    .A(_040_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _150_ (
    .A(_073_),
    .B(_077_),
    .Y(SUM[1])
  );
  NAND _151_ (
    .A(_042_),
    .B(_044_),
    .Y(_078_)
  );
  NAND _152_ (
    .A(_046_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _153_ (
    .A(_073_),
    .B(_079_),
    .Y(SUM[2])
  );
  NAND _154_ (
    .A(_048_),
    .B(_050_),
    .Y(_080_)
  );
  NAND _155_ (
    .A(_052_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _156_ (
    .A(_073_),
    .B(_081_),
    .Y(SUM[3])
  );
  NAND _157_ (
    .A(_054_),
    .B(_056_),
    .Y(_000_)
  );
  NAND _158_ (
    .A(_058_),
    .B(_000_),
    .Y(_001_)
  );
  NAND _159_ (
    .A(_073_),
    .B(_001_),
    .Y(SUM[4])
  );
  NAND _160_ (
    .A(_060_),
    .B(_062_),
    .Y(_002_)
  );
  NAND _161_ (
    .A(_064_),
    .B(_002_),
    .Y(_003_)
  );
  NAND _162_ (
    .A(_073_),
    .B(_003_),
    .Y(SUM[5])
  );
  NAND _163_ (
    .A(_066_),
    .B(_068_),
    .Y(_004_)
  );
  NAND _164_ (
    .A(_070_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _165_ (
    .A(_073_),
    .B(_005_),
    .Y(SUM[6])
  );
  NAND _166_ (
    .A(_011_),
    .B(_012_),
    .Y(_006_)
  );
  NAND _167_ (
    .A(_027_),
    .B(_006_),
    .Y(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand.v:3.7-3.31" *)
  NAND _168_ (
    .A(_007_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _169_ (
    .A(_071_),
    .B(_007_),
    .Y(_009_)
  );
  NAND _170_ (
    .A(_072_),
    .B(_008_),
    .Y(_010_)
  );
  NAND _171_ (
    .A(_009_),
    .B(_010_),
    .Y(SUM[7])
  );
endmodule
