/* Generated by Yosys 0.25+99 (git sha1 54bf15a5b, x86_64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "mult_stage.sv:5.1-44.10" *)
module mult_stage(clock, reset, start, mplier_in, mcand_in, product_in, done, mplier_out, mcand_out, product_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  (* src = "mult_stage.sv:6.24-6.29" *)
  input clock;
  wire clock;
  (* src = "mult_stage.sv:10.31-10.35" *)
  output done;
  reg done;
  (* src = "mult_stage.sv:7.29-7.37" *)
  input [7:0] mcand_in;
  wire [7:0] mcand_in;
  (* src = "mult_stage.sv:11.37-11.46" *)
  output [7:0] mcand_out;
  wire [7:0] mcand_out;
  (* src = "mult_stage.sv:7.18-7.27" *)
  input [7:0] mplier_in;
  wire [7:0] mplier_in;
  (* src = "mult_stage.sv:11.25-11.35" *)
  output [7:0] mplier_out;
  wire [7:0] mplier_out;
  (* src = "mult_stage.sv:18.31-18.41" *)
  wire [7:0] next_mcand;
  (* src = "mult_stage.sv:18.18-18.29" *)
  wire [7:0] next_mplier;
  (* src = "mult_stage.sv:17.45-17.65" *)
  wire [7:0] next_partial_product;
  (* src = "mult_stage.sv:17.31-17.43" *)
  reg [7:0] partial_prod;
  (* src = "mult_stage.sv:17.18-17.29" *)
  reg [7:0] prod_in_reg;
  (* src = "mult_stage.sv:8.18-8.28" *)
  input [7:0] product_in;
  wire [7:0] product_in;
  (* src = "mult_stage.sv:12.25-12.36" *)
  output [7:0] product_out;
  wire [7:0] product_out;
  (* src = "mult_stage.sv:6.31-6.36" *)
  input reset;
  wire reset;
  (* src = "mult_stage.sv:6.38-6.43" *)
  input start;
  wire start;
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _164_ (
    .A(reset),
    .B(reset),
    .Y(_115_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _165_ (
    .A(prod_in_reg[0]),
    .B(prod_in_reg[0]),
    .Y(_116_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _166_ (
    .A(partial_prod[0]),
    .B(partial_prod[0]),
    .Y(_117_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _167_ (
    .A(prod_in_reg[1]),
    .B(prod_in_reg[1]),
    .Y(_118_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _168_ (
    .A(partial_prod[1]),
    .B(partial_prod[1]),
    .Y(_119_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _169_ (
    .A(prod_in_reg[2]),
    .B(prod_in_reg[2]),
    .Y(_120_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _170_ (
    .A(partial_prod[2]),
    .B(partial_prod[2]),
    .Y(_121_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _171_ (
    .A(prod_in_reg[3]),
    .B(prod_in_reg[3]),
    .Y(_122_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _172_ (
    .A(partial_prod[3]),
    .B(partial_prod[3]),
    .Y(_123_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _173_ (
    .A(prod_in_reg[4]),
    .B(prod_in_reg[4]),
    .Y(_124_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _174_ (
    .A(partial_prod[4]),
    .B(partial_prod[4]),
    .Y(_125_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _175_ (
    .A(prod_in_reg[5]),
    .B(prod_in_reg[5]),
    .Y(_126_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _176_ (
    .A(partial_prod[5]),
    .B(partial_prod[5]),
    .Y(_127_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _177_ (
    .A(prod_in_reg[6]),
    .B(prod_in_reg[6]),
    .Y(_128_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _178_ (
    .A(partial_prod[6]),
    .B(partial_prod[6]),
    .Y(_129_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _179_ (
    .A(prod_in_reg[7]),
    .B(prod_in_reg[7]),
    .Y(_130_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _180_ (
    .A(partial_prod[7]),
    .B(partial_prod[7]),
    .Y(_131_)
  );
  NAND _181_ (
    .A(start),
    .B(_115_),
    .Y(_132_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _182_ (
    .A(_132_),
    .B(_132_),
    .Y(_000_)
  );
  NAND _183_ (
    .A(mcand_in[0]),
    .B(mplier_in[0]),
    .Y(_133_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _184_ (
    .A(_133_),
    .B(_133_),
    .Y(next_partial_product[0])
  );
  NAND _185_ (
    .A(prod_in_reg[0]),
    .B(partial_prod[0]),
    .Y(_134_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _186_ (
    .A(_134_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _187_ (
    .A(prod_in_reg[1]),
    .B(partial_prod[1]),
    .Y(_136_)
  );
  NAND _188_ (
    .A(_118_),
    .B(_119_),
    .Y(_137_)
  );
  NAND _189_ (
    .A(_136_),
    .B(_137_),
    .Y(_138_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _190_ (
    .A(_138_),
    .B(_138_),
    .Y(_139_)
  );
  NAND _191_ (
    .A(_135_),
    .B(_139_),
    .Y(_140_)
  );
  NAND _192_ (
    .A(_134_),
    .B(_138_),
    .Y(_141_)
  );
  NAND _193_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _194_ (
    .A(_142_),
    .B(_142_),
    .Y(product_out[1])
  );
  NAND _195_ (
    .A(_136_),
    .B(_140_),
    .Y(_143_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _196_ (
    .A(_143_),
    .B(_143_),
    .Y(_144_)
  );
  NAND _197_ (
    .A(prod_in_reg[2]),
    .B(partial_prod[2]),
    .Y(_145_)
  );
  NAND _198_ (
    .A(_120_),
    .B(_121_),
    .Y(_146_)
  );
  NAND _199_ (
    .A(_145_),
    .B(_146_),
    .Y(_147_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _200_ (
    .A(_147_),
    .B(_147_),
    .Y(_148_)
  );
  NAND _201_ (
    .A(_143_),
    .B(_148_),
    .Y(_149_)
  );
  NAND _202_ (
    .A(_144_),
    .B(_147_),
    .Y(_150_)
  );
  NAND _203_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _204_ (
    .A(_151_),
    .B(_151_),
    .Y(product_out[2])
  );
  NAND _205_ (
    .A(_145_),
    .B(_149_),
    .Y(_152_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _206_ (
    .A(_152_),
    .B(_152_),
    .Y(_153_)
  );
  NAND _207_ (
    .A(prod_in_reg[3]),
    .B(partial_prod[3]),
    .Y(_154_)
  );
  NAND _208_ (
    .A(_122_),
    .B(_123_),
    .Y(_155_)
  );
  NAND _209_ (
    .A(_154_),
    .B(_155_),
    .Y(_156_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _210_ (
    .A(_156_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _211_ (
    .A(_152_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _212_ (
    .A(_153_),
    .B(_156_),
    .Y(_159_)
  );
  NAND _213_ (
    .A(_158_),
    .B(_159_),
    .Y(_160_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _214_ (
    .A(_160_),
    .B(_160_),
    .Y(product_out[3])
  );
  NAND _215_ (
    .A(_154_),
    .B(_158_),
    .Y(_161_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _216_ (
    .A(_161_),
    .B(_161_),
    .Y(_162_)
  );
  NAND _217_ (
    .A(prod_in_reg[4]),
    .B(partial_prod[4]),
    .Y(_163_)
  );
  NAND _218_ (
    .A(_124_),
    .B(_125_),
    .Y(_001_)
  );
  NAND _219_ (
    .A(_163_),
    .B(_001_),
    .Y(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _220_ (
    .A(_002_),
    .B(_002_),
    .Y(_003_)
  );
  NAND _221_ (
    .A(_161_),
    .B(_003_),
    .Y(_004_)
  );
  NAND _222_ (
    .A(_162_),
    .B(_002_),
    .Y(_005_)
  );
  NAND _223_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _224_ (
    .A(_006_),
    .B(_006_),
    .Y(product_out[4])
  );
  NAND _225_ (
    .A(_163_),
    .B(_004_),
    .Y(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _226_ (
    .A(_007_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _227_ (
    .A(prod_in_reg[5]),
    .B(partial_prod[5]),
    .Y(_009_)
  );
  NAND _228_ (
    .A(_126_),
    .B(_127_),
    .Y(_010_)
  );
  NAND _229_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _230_ (
    .A(_011_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _231_ (
    .A(_007_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _232_ (
    .A(_008_),
    .B(_011_),
    .Y(_014_)
  );
  NAND _233_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _234_ (
    .A(_015_),
    .B(_015_),
    .Y(product_out[5])
  );
  NAND _235_ (
    .A(_009_),
    .B(_013_),
    .Y(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _236_ (
    .A(_016_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _237_ (
    .A(prod_in_reg[6]),
    .B(partial_prod[6]),
    .Y(_018_)
  );
  NAND _238_ (
    .A(_128_),
    .B(_129_),
    .Y(_019_)
  );
  NAND _239_ (
    .A(_018_),
    .B(_019_),
    .Y(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _240_ (
    .A(_020_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _241_ (
    .A(_016_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _242_ (
    .A(_017_),
    .B(_020_),
    .Y(_023_)
  );
  NAND _243_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _244_ (
    .A(_024_),
    .B(_024_),
    .Y(product_out[6])
  );
  NAND _245_ (
    .A(_018_),
    .B(_022_),
    .Y(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _246_ (
    .A(_025_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _247_ (
    .A(prod_in_reg[7]),
    .B(_131_),
    .Y(_027_)
  );
  NAND _248_ (
    .A(_130_),
    .B(partial_prod[7]),
    .Y(_028_)
  );
  NAND _249_ (
    .A(_130_),
    .B(_131_),
    .Y(_029_)
  );
  NAND _250_ (
    .A(prod_in_reg[7]),
    .B(partial_prod[7]),
    .Y(_030_)
  );
  NAND _251_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _252_ (
    .A(_027_),
    .B(_028_),
    .Y(_032_)
  );
  NAND _253_ (
    .A(_026_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _254_ (
    .A(_025_),
    .B(_031_),
    .Y(_034_)
  );
  NAND _255_ (
    .A(_033_),
    .B(_034_),
    .Y(product_out[7])
  );
  NAND _256_ (
    .A(_116_),
    .B(_117_),
    .Y(_035_)
  );
  NAND _257_ (
    .A(_134_),
    .B(_035_),
    .Y(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _258_ (
    .A(_036_),
    .B(_036_),
    .Y(product_out[0])
  );
  NAND _259_ (
    .A(mplier_in[0]),
    .B(mcand_in[1]),
    .Y(_037_)
  );
  NAND _260_ (
    .A(mcand_in[0]),
    .B(mplier_in[1]),
    .Y(_038_)
  );
  NAND _261_ (
    .A(mcand_in[1]),
    .B(mplier_in[1]),
    .Y(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _262_ (
    .A(_039_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _263_ (
    .A(next_partial_product[0]),
    .B(_040_),
    .Y(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _264_ (
    .A(_041_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _265_ (
    .A(mplier_in[0]),
    .B(mcand_in[2]),
    .Y(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _266_ (
    .A(_043_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _267_ (
    .A(mcand_in[2]),
    .B(mplier_in[1]),
    .Y(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _268_ (
    .A(_045_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _269_ (
    .A(_040_),
    .B(_044_),
    .Y(_047_)
  );
  NAND _270_ (
    .A(_039_),
    .B(_043_),
    .Y(_048_)
  );
  NAND _271_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _272_ (
    .A(_049_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _273_ (
    .A(_042_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _274_ (
    .A(_041_),
    .B(_049_),
    .Y(_052_)
  );
  NAND _275_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _276_ (
    .A(_053_),
    .B(_053_),
    .Y(next_partial_product[2])
  );
  NAND _277_ (
    .A(_047_),
    .B(_051_),
    .Y(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _278_ (
    .A(_054_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _279_ (
    .A(mplier_in[0]),
    .B(mcand_in[3]),
    .Y(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _280_ (
    .A(_056_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _281_ (
    .A(mcand_in[3]),
    .B(mplier_in[1]),
    .Y(_058_)
  );
  NAND _282_ (
    .A(_046_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _283_ (
    .A(_045_),
    .B(_056_),
    .Y(_060_)
  );
  NAND _284_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _285_ (
    .A(_061_),
    .B(_061_),
    .Y(_062_)
  );
  NAND _286_ (
    .A(_054_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _287_ (
    .A(_055_),
    .B(_061_),
    .Y(_064_)
  );
  NAND _288_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _289_ (
    .A(_065_),
    .B(_065_),
    .Y(next_partial_product[3])
  );
  NAND _290_ (
    .A(_059_),
    .B(_063_),
    .Y(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _291_ (
    .A(_066_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _292_ (
    .A(mplier_in[0]),
    .B(mcand_in[4]),
    .Y(_068_)
  );
  NAND _293_ (
    .A(mcand_in[4]),
    .B(mplier_in[1]),
    .Y(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _294_ (
    .A(_069_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _295_ (
    .A(_057_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _296_ (
    .A(_058_),
    .B(_068_),
    .Y(_072_)
  );
  NAND _297_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _298_ (
    .A(_073_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _299_ (
    .A(_066_),
    .B(_074_),
    .Y(_075_)
  );
  NAND _300_ (
    .A(_067_),
    .B(_073_),
    .Y(_076_)
  );
  NAND _301_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _302_ (
    .A(_077_),
    .B(_077_),
    .Y(next_partial_product[4])
  );
  NAND _303_ (
    .A(_071_),
    .B(_075_),
    .Y(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _304_ (
    .A(_078_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _305_ (
    .A(mplier_in[0]),
    .B(mcand_in[5]),
    .Y(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _306_ (
    .A(_080_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _307_ (
    .A(mcand_in[5]),
    .B(mplier_in[1]),
    .Y(_082_)
  );
  NAND _308_ (
    .A(_070_),
    .B(_081_),
    .Y(_083_)
  );
  NAND _309_ (
    .A(_069_),
    .B(_080_),
    .Y(_084_)
  );
  NAND _310_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _311_ (
    .A(_085_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _312_ (
    .A(_078_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _313_ (
    .A(_079_),
    .B(_085_),
    .Y(_088_)
  );
  NAND _314_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _315_ (
    .A(_089_),
    .B(_089_),
    .Y(next_partial_product[5])
  );
  NAND _316_ (
    .A(_083_),
    .B(_087_),
    .Y(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _317_ (
    .A(_090_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _318_ (
    .A(mplier_in[0]),
    .B(mcand_in[6]),
    .Y(_092_)
  );
  NAND _319_ (
    .A(mcand_in[6]),
    .B(mplier_in[1]),
    .Y(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _320_ (
    .A(_093_),
    .B(_093_),
    .Y(_094_)
  );
  NAND _321_ (
    .A(_081_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _322_ (
    .A(_082_),
    .B(_092_),
    .Y(_096_)
  );
  NAND _323_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _324_ (
    .A(_097_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _325_ (
    .A(_090_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _326_ (
    .A(_091_),
    .B(_097_),
    .Y(_100_)
  );
  NAND _327_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _328_ (
    .A(_101_),
    .B(_101_),
    .Y(next_partial_product[6])
  );
  NAND _329_ (
    .A(_095_),
    .B(_099_),
    .Y(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _330_ (
    .A(_102_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _331_ (
    .A(mplier_in[0]),
    .B(mcand_in[7]),
    .Y(_104_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _332_ (
    .A(_104_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _333_ (
    .A(_093_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _334_ (
    .A(_094_),
    .B(_104_),
    .Y(_107_)
  );
  NAND _335_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _336_ (
    .A(_108_),
    .B(_108_),
    .Y(_109_)
  );
  NAND _337_ (
    .A(_103_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _338_ (
    .A(_102_),
    .B(_108_),
    .Y(_111_)
  );
  NAND _339_ (
    .A(_110_),
    .B(_111_),
    .Y(_112_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _340_ (
    .A(_112_),
    .B(_112_),
    .Y(next_partial_product[7])
  );
  NAND _341_ (
    .A(_037_),
    .B(_038_),
    .Y(_113_)
  );
  NAND _342_ (
    .A(_041_),
    .B(_113_),
    .Y(_114_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../Cells/all2nand_reg.v:3.7-3.31" *)
  NAND _343_ (
    .A(_114_),
    .B(_114_),
    .Y(next_partial_product[1])
  );
  reg \mplier_out_reg[3] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    \mplier_out_reg[3]  <= mplier_in[5];
  assign mplier_out[3] = \mplier_out_reg[3] ;
  reg \mplier_out_reg[4] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    \mplier_out_reg[4]  <= mplier_in[6];
  assign mplier_out[4] = \mplier_out_reg[4] ;
  reg \mplier_out_reg[5] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    \mplier_out_reg[5]  <= mplier_in[7];
  assign mplier_out[5] = \mplier_out_reg[5] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[0] <= product_in[0];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[1] <= product_in[1];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[2] <= product_in[2];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[3] <= product_in[3];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[4] <= product_in[4];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[5] <= product_in[5];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[6] <= product_in[6];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    prod_in_reg[7] <= product_in[7];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[0] <= next_partial_product[0];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[1] <= next_partial_product[1];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[2] <= next_partial_product[2];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[3] <= next_partial_product[3];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[4] <= next_partial_product[4];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[5] <= next_partial_product[5];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[6] <= next_partial_product[6];
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    partial_prod[7] <= next_partial_product[7];
  (* src = "mult_stage.sv:36.2-42.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    done <= _000_;
  reg \mplier_out_reg[0] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    \mplier_out_reg[0]  <= mplier_in[2];
  assign mplier_out[0] = \mplier_out_reg[0] ;
  reg \mplier_out_reg[1] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    \mplier_out_reg[1]  <= mplier_in[3];
  assign mplier_out[1] = \mplier_out_reg[1] ;
  reg \mplier_out_reg[2] ;
  (* src = "mult_stage.sv:28.2-33.5|../../Cells/all2nand_reg.v:17.1-18.9" *)
  always @(posedge clock)
    \mplier_out_reg[2]  <= mplier_in[4];
  assign mplier_out[2] = \mplier_out_reg[2] ;
  assign mcand_out = 8'h00;
  assign mplier_out[7:6] = 2'h0;
  assign next_mcand = 8'h00;
  assign next_mplier = { 2'h0, mplier_in[7:2] };
endmodule
