/* Generated by Yosys 0.25+99 (git sha1 54bf15a5b, x86_64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "shift_reg_mem_comb.sv:1.1-24.10" *)
module shift_reg_mem_comb(write_data, shift_reg, write_enable, shift_reg_next);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  (* src = "shift_reg_mem_comb.sv:3.25-3.34" *)
  input [31:0] shift_reg;
  wire [31:0] shift_reg;
  (* src = "shift_reg_mem_comb.sv:5.26-5.40" *)
  output [31:0] shift_reg_next;
  wire [31:0] shift_reg_next;
  (* src = "shift_reg_mem_comb.sv:2.25-2.35" *)
  input [31:0] write_data;
  wire [31:0] write_data;
  (* src = "shift_reg_mem_comb.sv:4.11-4.23" *)
  input write_enable;
  wire write_enable;
  (* module_not_derived = 32'd1 *)
  (* src = "../Cells/all2nand.v:3.7-3.31" *)
  NAND _064_ (
    .A(write_enable),
    .B(write_enable),
    .Y(_061_)
  );
  NAND _065_ (
    .A(write_data[31]),
    .B(write_enable),
    .Y(_062_)
  );
  NAND _066_ (
    .A(shift_reg[30]),
    .B(_061_),
    .Y(_063_)
  );
  NAND _067_ (
    .A(_062_),
    .B(_063_),
    .Y(shift_reg_next[31])
  );
  NAND _068_ (
    .A(write_enable),
    .B(write_data[30]),
    .Y(_000_)
  );
  NAND _069_ (
    .A(_061_),
    .B(shift_reg[29]),
    .Y(_001_)
  );
  NAND _070_ (
    .A(_000_),
    .B(_001_),
    .Y(shift_reg_next[30])
  );
  NAND _071_ (
    .A(write_enable),
    .B(write_data[29]),
    .Y(_002_)
  );
  NAND _072_ (
    .A(_061_),
    .B(shift_reg[28]),
    .Y(_003_)
  );
  NAND _073_ (
    .A(_002_),
    .B(_003_),
    .Y(shift_reg_next[29])
  );
  NAND _074_ (
    .A(write_enable),
    .B(write_data[28]),
    .Y(_004_)
  );
  NAND _075_ (
    .A(_061_),
    .B(shift_reg[27]),
    .Y(_005_)
  );
  NAND _076_ (
    .A(_004_),
    .B(_005_),
    .Y(shift_reg_next[28])
  );
  NAND _077_ (
    .A(write_enable),
    .B(write_data[27]),
    .Y(_006_)
  );
  NAND _078_ (
    .A(_061_),
    .B(shift_reg[26]),
    .Y(_007_)
  );
  NAND _079_ (
    .A(_006_),
    .B(_007_),
    .Y(shift_reg_next[27])
  );
  NAND _080_ (
    .A(write_enable),
    .B(write_data[26]),
    .Y(_008_)
  );
  NAND _081_ (
    .A(_061_),
    .B(shift_reg[25]),
    .Y(_009_)
  );
  NAND _082_ (
    .A(_008_),
    .B(_009_),
    .Y(shift_reg_next[26])
  );
  NAND _083_ (
    .A(write_enable),
    .B(write_data[25]),
    .Y(_010_)
  );
  NAND _084_ (
    .A(_061_),
    .B(shift_reg[24]),
    .Y(_011_)
  );
  NAND _085_ (
    .A(_010_),
    .B(_011_),
    .Y(shift_reg_next[25])
  );
  NAND _086_ (
    .A(write_enable),
    .B(write_data[24]),
    .Y(_012_)
  );
  NAND _087_ (
    .A(_061_),
    .B(shift_reg[23]),
    .Y(_013_)
  );
  NAND _088_ (
    .A(_012_),
    .B(_013_),
    .Y(shift_reg_next[24])
  );
  NAND _089_ (
    .A(write_enable),
    .B(write_data[23]),
    .Y(_014_)
  );
  NAND _090_ (
    .A(_061_),
    .B(shift_reg[22]),
    .Y(_015_)
  );
  NAND _091_ (
    .A(_014_),
    .B(_015_),
    .Y(shift_reg_next[23])
  );
  NAND _092_ (
    .A(write_enable),
    .B(write_data[22]),
    .Y(_016_)
  );
  NAND _093_ (
    .A(_061_),
    .B(shift_reg[21]),
    .Y(_017_)
  );
  NAND _094_ (
    .A(_016_),
    .B(_017_),
    .Y(shift_reg_next[22])
  );
  NAND _095_ (
    .A(write_enable),
    .B(write_data[21]),
    .Y(_018_)
  );
  NAND _096_ (
    .A(_061_),
    .B(shift_reg[20]),
    .Y(_019_)
  );
  NAND _097_ (
    .A(_018_),
    .B(_019_),
    .Y(shift_reg_next[21])
  );
  NAND _098_ (
    .A(write_enable),
    .B(write_data[20]),
    .Y(_020_)
  );
  NAND _099_ (
    .A(_061_),
    .B(shift_reg[19]),
    .Y(_021_)
  );
  NAND _100_ (
    .A(_020_),
    .B(_021_),
    .Y(shift_reg_next[20])
  );
  NAND _101_ (
    .A(write_enable),
    .B(write_data[19]),
    .Y(_022_)
  );
  NAND _102_ (
    .A(_061_),
    .B(shift_reg[18]),
    .Y(_023_)
  );
  NAND _103_ (
    .A(_022_),
    .B(_023_),
    .Y(shift_reg_next[19])
  );
  NAND _104_ (
    .A(write_enable),
    .B(write_data[18]),
    .Y(_024_)
  );
  NAND _105_ (
    .A(_061_),
    .B(shift_reg[17]),
    .Y(_025_)
  );
  NAND _106_ (
    .A(_024_),
    .B(_025_),
    .Y(shift_reg_next[18])
  );
  NAND _107_ (
    .A(write_enable),
    .B(write_data[17]),
    .Y(_026_)
  );
  NAND _108_ (
    .A(_061_),
    .B(shift_reg[16]),
    .Y(_027_)
  );
  NAND _109_ (
    .A(_026_),
    .B(_027_),
    .Y(shift_reg_next[17])
  );
  NAND _110_ (
    .A(write_enable),
    .B(write_data[16]),
    .Y(_028_)
  );
  NAND _111_ (
    .A(_061_),
    .B(shift_reg[15]),
    .Y(_029_)
  );
  NAND _112_ (
    .A(_028_),
    .B(_029_),
    .Y(shift_reg_next[16])
  );
  NAND _113_ (
    .A(write_enable),
    .B(write_data[15]),
    .Y(_030_)
  );
  NAND _114_ (
    .A(_061_),
    .B(shift_reg[14]),
    .Y(_031_)
  );
  NAND _115_ (
    .A(_030_),
    .B(_031_),
    .Y(shift_reg_next[15])
  );
  NAND _116_ (
    .A(write_enable),
    .B(write_data[14]),
    .Y(_032_)
  );
  NAND _117_ (
    .A(_061_),
    .B(shift_reg[13]),
    .Y(_033_)
  );
  NAND _118_ (
    .A(_032_),
    .B(_033_),
    .Y(shift_reg_next[14])
  );
  NAND _119_ (
    .A(write_enable),
    .B(write_data[13]),
    .Y(_034_)
  );
  NAND _120_ (
    .A(_061_),
    .B(shift_reg[12]),
    .Y(_035_)
  );
  NAND _121_ (
    .A(_034_),
    .B(_035_),
    .Y(shift_reg_next[13])
  );
  NAND _122_ (
    .A(write_enable),
    .B(write_data[12]),
    .Y(_036_)
  );
  NAND _123_ (
    .A(_061_),
    .B(shift_reg[11]),
    .Y(_037_)
  );
  NAND _124_ (
    .A(_036_),
    .B(_037_),
    .Y(shift_reg_next[12])
  );
  NAND _125_ (
    .A(write_enable),
    .B(write_data[11]),
    .Y(_038_)
  );
  NAND _126_ (
    .A(_061_),
    .B(shift_reg[10]),
    .Y(_039_)
  );
  NAND _127_ (
    .A(_038_),
    .B(_039_),
    .Y(shift_reg_next[11])
  );
  NAND _128_ (
    .A(write_enable),
    .B(write_data[10]),
    .Y(_040_)
  );
  NAND _129_ (
    .A(_061_),
    .B(shift_reg[9]),
    .Y(_041_)
  );
  NAND _130_ (
    .A(_040_),
    .B(_041_),
    .Y(shift_reg_next[10])
  );
  NAND _131_ (
    .A(write_enable),
    .B(write_data[9]),
    .Y(_042_)
  );
  NAND _132_ (
    .A(_061_),
    .B(shift_reg[8]),
    .Y(_043_)
  );
  NAND _133_ (
    .A(_042_),
    .B(_043_),
    .Y(shift_reg_next[9])
  );
  NAND _134_ (
    .A(write_enable),
    .B(write_data[8]),
    .Y(_044_)
  );
  NAND _135_ (
    .A(_061_),
    .B(shift_reg[7]),
    .Y(_045_)
  );
  NAND _136_ (
    .A(_044_),
    .B(_045_),
    .Y(shift_reg_next[8])
  );
  NAND _137_ (
    .A(write_enable),
    .B(write_data[7]),
    .Y(_046_)
  );
  NAND _138_ (
    .A(_061_),
    .B(shift_reg[6]),
    .Y(_047_)
  );
  NAND _139_ (
    .A(_046_),
    .B(_047_),
    .Y(shift_reg_next[7])
  );
  NAND _140_ (
    .A(write_enable),
    .B(write_data[6]),
    .Y(_048_)
  );
  NAND _141_ (
    .A(_061_),
    .B(shift_reg[5]),
    .Y(_049_)
  );
  NAND _142_ (
    .A(_048_),
    .B(_049_),
    .Y(shift_reg_next[6])
  );
  NAND _143_ (
    .A(write_enable),
    .B(write_data[5]),
    .Y(_050_)
  );
  NAND _144_ (
    .A(_061_),
    .B(shift_reg[4]),
    .Y(_051_)
  );
  NAND _145_ (
    .A(_050_),
    .B(_051_),
    .Y(shift_reg_next[5])
  );
  NAND _146_ (
    .A(write_enable),
    .B(write_data[4]),
    .Y(_052_)
  );
  NAND _147_ (
    .A(_061_),
    .B(shift_reg[3]),
    .Y(_053_)
  );
  NAND _148_ (
    .A(_052_),
    .B(_053_),
    .Y(shift_reg_next[4])
  );
  NAND _149_ (
    .A(write_enable),
    .B(write_data[3]),
    .Y(_054_)
  );
  NAND _150_ (
    .A(_061_),
    .B(shift_reg[2]),
    .Y(_055_)
  );
  NAND _151_ (
    .A(_054_),
    .B(_055_),
    .Y(shift_reg_next[3])
  );
  NAND _152_ (
    .A(write_enable),
    .B(write_data[2]),
    .Y(_056_)
  );
  NAND _153_ (
    .A(_061_),
    .B(shift_reg[1]),
    .Y(_057_)
  );
  NAND _154_ (
    .A(_056_),
    .B(_057_),
    .Y(shift_reg_next[2])
  );
  NAND _155_ (
    .A(write_enable),
    .B(write_data[1]),
    .Y(_058_)
  );
  NAND _156_ (
    .A(_061_),
    .B(shift_reg[0]),
    .Y(_059_)
  );
  NAND _157_ (
    .A(_058_),
    .B(_059_),
    .Y(shift_reg_next[1])
  );
  NAND _158_ (
    .A(write_enable),
    .B(write_data[0]),
    .Y(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../Cells/all2nand.v:3.7-3.31" *)
  NAND _159_ (
    .A(_060_),
    .B(_060_),
    .Y(shift_reg_next[0])
  );
endmodule
